version: "3.7"

services:
  dbKufar:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: trytofindme


  adminer2:
    image: adminer
    restart: always
    ports:
      - 15520:8080
    depends_on:
      - dbKufar

      
  parser_kufar:
    build:
      context: ./parser
      dockerfile: prod.Dockerfile  
    restart: always
    ports:
      - 20001:20001
    volumes:
      - /home/projects/Kufar-parser:/usr/src/app/logs/output_log
    depends_on:
      - dbKufar