version: "3.7"

services:
  dbKufar:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: trytofindme
    volumes:
      - ./db_Kufar/db_prod:/var/lib/postgresql/data


  adminer2:
    image: adminer
    restart: always
    ports:
      - 15520:8080
    depends_on:
      - dbKufar

      
  parserKufar:
    build:
      context: ./parser
      dockerfile: prod.Dockerfile  
    restart: always
    ports:
      - 20001:20001
    volumes:
      - /home/parser_log:/usr/src/app/logs/output_log
    depends_on:
      - dbKufar